### ISSUE TITLE
Build Errors w/ Eclipse IDE (Maven Project)

### ISSUE THREAD

**Issue by behollister** [agdturner/ccg-v3d#2]
Proceeding with build instructions for a Maven Project. Getting the build errors shown here in Eclipse IDE:
![errors](https://user-images.githubusercontent.com/20388050/170152978-88971cb9-9189-4cb2-a9f1-d333e15994fd.png)
Related to JOSS review: https://github.com/openjournals/joss-reviews/issues/4283

**Comment by agdturner** [comment]
I am not familiar with Eclipse recently. I presume you have loaded the
project as a Maven project. What are the issues at the top level? - Why is
there a red cross? Have you tried compiling in src/main/java. I am not sure
why the src folder is added in the top level, did Eclipse do this, or did
you decide that was what should be done?

**Comment by agdturner** [comment]
The project opens fine for me in Eclipse:
![image](https://user-images.githubusercontent.com/5878594/170243220-3212ac1b-443f-4fc6-81a3-ee6cd5245cf0.png)

**Comment by agdturner** [comment]
I used the latest Eclipse download for this and the following procedure from https://vaadin.com/learn/tutorials/import-maven-project-eclipse: Import the project:
- In Eclipse, select File > Import… ​
- In the import window, expand Maven, select Existing Maven Projects, and click Next
- Click Browse and select the directory that contains the pom.xml file of the project you want to import
- Click Finish

**Comment by behollister** [comment]
The "[ERROR] symbol: class Math_Quaternion_BigRational" is likely a path issue for finding the library definition of Math_Quanternion_BigRational. 

Which library / package is that from exactly? I'm not that familiar with Maven, but it appears it is downloading and installing dependencies. 

Is it possible that the configuration (POM.xml) is missing a dependency, but that your dev platform has it? 

I'm using the process you mention. After invoking Run As -> Maven Install (from the project explorer), I get the following. See COMPILATION ERROR below.

[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< io.github.agdturner:ccg-v3d >---------------------
[INFO] Building ccg-v3d 0.15-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/3.0.0-M4/maven-surefire-plugin-3.0.0-M4.pom
[INFO] Downloaded from : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/3.0.0-M4/maven-surefire-plugin-3.0.0-M4.pom (8.1 kB at 4.4 kB/s)
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/3.0.0-M4/surefire-3.0.0-M4.pom
[INFO] Downloaded from : https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/3.0.0-M4/surefire-3.0.0-M4.pom (27 kB at 130 kB/s)
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.pom
[INFO] Downloaded from : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.4/maven-jar-plugin-2.4.pom (5.8 kB at 35 kB/s)
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom
[INFO] Downloaded from : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom (13 kB at 58 kB/s)
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom
[INFO] Downloaded from : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom (6.4 kB at 24 kB/s)
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ccg-v3d ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/brad/develop/JOSS-review/ccg-v3d/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ ccg-v3d ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 27 source files to /home/brad/develop/JOSS-review/ccg-v3d/target/classes
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/light/V3D_VGeometry.java]]
[parsing completed 25ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Points.java]]
[parsing completed 14ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Tetrahedron.java]]
[parsing completed 43ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_IntersectionAndDistanceCalculations.java]]
[parsing completed 5ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Point.java]]
[parsing completed 47ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_LineSegment.java]]
[parsing completed 53ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/module-info.java]]
[parsing completed 3ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/light/V3D_VTriangle.java]]
[parsing completed 2ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Envelope.java]]
[parsing completed 68ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/light/V3D_VTetrahedron.java]]
[parsing completed 2ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Face.java]]
[parsing completed 1ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Ray.java]]
[parsing completed 14ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Line.java]]
[parsing completed 24ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/light/V3D_VLine.java]]
[parsing completed 2ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_TrianglesCoplanar.java]]
[parsing completed 6ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/light/V3D_V.java]]
[parsing completed 3ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Plane.java]]
[parsing completed 19ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/light/V3D_VPoint.java]]
[parsing completed 3ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Rectangle.java]]
[parsing completed 10ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_FiniteGeometry.java]]
[parsing completed 0ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java]]
[parsing completed 7ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Tetrahedrons.java]]
[parsing completed 4ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_LineSegmentsCollinear.java]]
[parsing completed 7ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Geometry.java]]
[parsing completed 2ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/core/V3D_Environment.java]]
[parsing completed 2ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Triangle.java]]
[parsing completed 38ms]
[parsing started SimpleFileObject[/home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Volume.java]]
[parsing completed 1ms]
[loading /home/brad/.m2/repository/io/github/agdturner/ccg-math/2.0.10/ccg-math-2.0.10.jar(/module-info.class)]
[loading /home/brad/.m2/repository/io/github/agdturner/ccg-io/1.1.0/ccg-io-1.1.0.jar(/module-info.class)]
[loading /modules/java.base/module-info.class]
[loading /modules/java.desktop/module-info.class]
[loading /modules/java.xml/module-info.class]
[loading /modules/java.datatransfer/module-info.class]
[loading /modules/java.prefs/module-info.class]
[loading /modules/java.logging/module-info.class]
[loading /modules/java.base/java/io/Serializable.class]
[loading /modules/java.base/java/lang/Object.class]
[loading /modules/java.base/java/util/Objects.class]
[loading /home/brad/.m2/repository/io/github/agdturner/ccg-math/2.0.10/ccg-math-2.0.10.jar(/uk/ac/leeds/ccg/math/number/Math_BigRational.class)]
[loading /home/brad/.m2/repository/io/github/agdturner/ccg-math/2.0.10/ccg-math-2.0.10.jar(/uk/ac/leeds/ccg/math/number/Math_BigRationalSqrt.class)]
[loading /modules/java.base/java/math/BigDecimal.class]
[loading /modules/java.base/java/lang/Comparable.class]
[loading /home/brad/.m2/repository/ch/obermuhlner/big-math/2.3.0/big-math-2.3.0.jar(/ch/obermuhlner/math/big/BigDecimalMath.class)]
[loading /modules/java.base/java/math/MathContext.class]
[loading /home/brad/.m2/repository/io/github/agdturner/ccg-math/2.0.10/ccg-math-2.0.10.jar(/uk/ac/leeds/ccg/math/arithmetic/Math_BigInteger.class)]
[loading /modules/java.base/java/lang/String.class]
[loading /home/brad/.m2/repository/io/github/agdturner/ccg-math/2.0.10/ccg-math-2.0.10.jar(/uk/ac/leeds/ccg/math/arithmetic/Math_BigDecimal.class)]
[loading /home/brad/.m2/repository/io/github/agdturner/ccg-math/2.0.10/ccg-math-2.0.10.jar(/uk/ac/leeds/ccg/math/matrices/Math_Matrix_BR.class)]
[loading /modules/java.base/java/util/HashSet.class]
[loading /modules/java.base/java/util/Iterator.class]
[loading /modules/java.base/java/util/Arrays.class]
[loading /modules/java.base/java/util/List.class]
[loading /modules/java.base/java/util/Set.class]
[loading /modules/java.base/java/lang/Deprecated.class]
[loading /modules/java.base/java/lang/Override.class]
[loading /modules/java.base/java/lang/annotation/Annotation.class]
[loading /modules/java.base/java/lang/annotation/Retention.class]
[loading /modules/java.base/java/lang/annotation/RetentionPolicy.class]
[loading /modules/java.base/java/lang/annotation/Target.class]
[loading /modules/java.base/java/lang/annotation/ElementType.class]
[checking <anonymous >]
[checking uk.ac.leeds.ccg.v3d.geometry.light.V3D_VGeometry]
[loading /modules/java.base/java/lang/AutoCloseable.class]
[checking uk.ac.leeds.ccg.v3d.geometry.light.V3D_V]
[loading /modules/java.base/java/math/BigInteger.class]
[loading /modules/java.base/java/lang/Number.class]
[loading /modules/java.base/java/lang/Class.class]
[loading /modules/java.base/java/lang/reflect/GenericDeclaration.class]
[loading /modules/java.base/java/lang/reflect/AnnotatedElement.class]
[loading /modules/java.base/java/lang/reflect/Type.class]
[loading /modules/java.base/java/lang/invoke/TypeDescriptor.class]
[loading /modules/java.base/java/lang/invoke/TypeDescriptor$OfField.class]
[loading /modules/java.base/java/lang/constant/Constable.class]
[loading /modules/java.base/java/lang/Byte.class]
[loading /modules/java.base/java/lang/Character.class]
[loading /modules/java.base/java/lang/Short.class]
[loading /modules/java.base/java/lang/Long.class]
[loading /modules/java.base/java/lang/Float.class]
[loading /modules/java.base/java/lang/Integer.class]
[loading /modules/java.base/java/lang/Double.class]
[loading /modules/java.base/java/lang/Boolean.class]
[loading /modules/java.base/java/lang/Void.class]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_Point]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_Geometry]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_IntersectionAndDistanceCalculations]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_FiniteGeometry]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_Vector]
[checking uk.ac.leeds.ccg.v3d.geometry.light.V3D_VPoint]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_Envelope]
[loading /modules/java.base/java/lang/RuntimeException.class]
[loading /modules/java.base/java/lang/Throwable.class]
[loading /modules/java.base/java/lang/Exception.class]
[loading /modules/java.base/java/lang/UnsupportedOperationException.class]
[checking uk.ac.leeds.ccg.v3d.core.V3D_Environment]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_Line]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_LineSegment]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_Ray]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_Plane]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_Triangle]
[loading /modules/java.base/java/util/Collection.class]
[loading /modules/java.base/java/lang/Iterable.class]
[loading /modules/java.base/java/lang/Cloneable.class]
[loading /modules/java.base/java/util/AbstractSet.class]
[loading /modules/java.base/java/util/AbstractCollection.class]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_Face]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_Tetrahedron]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_Volume]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_Points]
[checking uk.ac.leeds.ccg.v3d.geometry.light.V3D_VTriangle]
[checking uk.ac.leeds.ccg.v3d.geometry.light.V3D_VTetrahedron]
[checking uk.ac.leeds.ccg.v3d.geometry.light.V3D_VLine]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_TrianglesCoplanar]
[loading /modules/java.base/java/util/function/IntFunction.class]
[loading /modules/java.base/java/util/stream/Stream.class]
[loading /modules/java.base/java/util/stream/BaseStream.class]
[loading /modules/java.base/java/util/function/Predicate.class]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_Rectangle]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_Tetrahedrons]
[loading /modules/java.base/java/util/Optional.class]
[loading /modules/java.base/java/lang/StringBuilder.class]
[loading /modules/java.base/java/lang/CharSequence.class]
[loading /modules/java.base/java/lang/AbstractStringBuilder.class]
[loading /modules/java.base/java/lang/Appendable.class]
[loading /modules/java.base/java/lang/StringBuffer.class]
[loading /modules/java.base/java/lang/constant/ConstantDesc.class]
[loading /modules/java.base/java/util/function/Consumer.class]
[checking uk.ac.leeds.ccg.v3d.geometry.V3D_LineSegmentsCollinear]
[total 2203ms]
[INFO] -------------------------------------------------------------
**[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[25,35] cannot find symbol
  symbol:   class Math_Quaternion_BigRational
  location: package uk.ac.leeds.ccg.math.number
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[427,39] cannot find symbol
  symbol:   method round(int)
  location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[428,39] cannot find symbol
  symbol:   method round(int)
  location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[429,39] cannot find symbol
  symbol:   method round(int)
  location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[707,50] cannot find symbol
  symbol:   method sin(uk.ac.leeds.ccg.math.arithmetic.Math_BigInteger,int)
  location: variable thetaDiv2 of type uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[708,39] cannot find symbol
  symbol:   method cos(uk.ac.leeds.ccg.math.arithmetic.Math_BigInteger,int)
  location: variable thetaDiv2 of type uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[712,9] cannot find symbol
  symbol:   class Math_Quaternion_BigRational
  location: class uk.ac.leeds.ccg.v3d.geometry.V3D_Vector
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[712,45] cannot find symbol
  symbol:   class Math_Quaternion_BigRational
  location: class uk.ac.leeds.ccg.v3d.geometry.V3D_Vector
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[715,9] cannot find symbol
  symbol:   class Math_Quaternion_BigRational
  location: class uk.ac.leeds.ccg.v3d.geometry.V3D_Vector
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[715,46] cannot find symbol
  symbol:   class Math_Quaternion_BigRational
  location: class uk.ac.leeds.ccg.v3d.geometry.V3D_Vector
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[717,9] cannot find symbol
  symbol:   class Math_Quaternion_BigRational
  location: class uk.ac.leeds.ccg.v3d.geometry.V3D_Vector
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[717,45] cannot find symbol
  symbol:   class Math_Quaternion_BigRational
  location: class uk.ac.leeds.ccg.v3d.geometry.V3D_Vector
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[721,9] cannot find symbol
  symbol:   class Math_Quaternion_BigRational
  location: class uk.ac.leeds.ccg.v3d.geometry.V3D_Vector
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Triangle.java:[882,48] cannot find symbol
  symbol:   method round(int)
  location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Triangle.java:[884,48] cannot find symbol
  symbol:   method round(int)
  location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Triangle.java:[886,48] cannot find symbol
  symbol:   method round(int)
  location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Tetrahedron.java:[333,68] cannot find symbol
  symbol:   method round(int)
  location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Tetrahedron.java:[335,68] cannot find symbol
  symbol:   method round(int)
  location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Tetrahedron.java:[337,68] cannot find symbol
  symbol:   method round(int)
  location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[INFO] 19 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.734 s
[INFO] Finished at: 2022-05-25T11:58:00-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project ccg-v3d: Compilation failure: Compilation failure: 
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[25,35] cannot find symbol
[ERROR]   symbol:   class Math_Quaternion_BigRational
[ERROR]   location: package uk.ac.leeds.ccg.math.number
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[427,39] cannot find symbol
[ERROR]   symbol:   method round(int)
[ERROR]   location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[428,39] cannot find symbol
[ERROR]   symbol:   method round(int)
[ERROR]   location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[429,39] cannot find symbol
[ERROR]   symbol:   method round(int)
[ERROR]   location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[707,50] cannot find symbol
[ERROR]   symbol:   method sin(uk.ac.leeds.ccg.math.arithmetic.Math_BigInteger,int)
[ERROR]   location: variable thetaDiv2 of type uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[708,39] cannot find symbol
[ERROR]   symbol:   method cos(uk.ac.leeds.ccg.math.arithmetic.Math_BigInteger,int)
[ERROR]   location: variable thetaDiv2 of type uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[712,9] cannot find symbol
[ERROR]   symbol:   class Math_Quaternion_BigRational
[ERROR]   location: class uk.ac.leeds.ccg.v3d.geometry.V3D_Vector
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[712,45] cannot find symbol
[ERROR]   symbol:   class Math_Quaternion_BigRational
[ERROR]   location: class uk.ac.leeds.ccg.v3d.geometry.V3D_Vector
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[715,9] cannot find symbol
[ERROR]   symbol:   class Math_Quaternion_BigRational
[ERROR]   location: class uk.ac.leeds.ccg.v3d.geometry.V3D_Vector
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[715,46] cannot find symbol
[ERROR]   symbol:   class Math_Quaternion_BigRational
[ERROR]   location: class uk.ac.leeds.ccg.v3d.geometry.V3D_Vector
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[717,9] cannot find symbol
[ERROR]   symbol:   class Math_Quaternion_BigRational
[ERROR]   location: class uk.ac.leeds.ccg.v3d.geometry.V3D_Vector
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[717,45] cannot find symbol
[ERROR]   symbol:   class Math_Quaternion_BigRational
[ERROR]   location: class uk.ac.leeds.ccg.v3d.geometry.V3D_Vector
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Vector.java:[721,9] cannot find symbol
[ERROR]   symbol:   class Math_Quaternion_BigRational
[ERROR]   location: class uk.ac.leeds.ccg.v3d.geometry.V3D_Vector
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Triangle.java:[882,48] cannot find symbol
[ERROR]   symbol:   method round(int)
[ERROR]   location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Triangle.java:[884,48] cannot find symbol
[ERROR]   symbol:   method round(int)
[ERROR]   location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Triangle.java:[886,48] cannot find symbol
[ERROR]   symbol:   method round(int)
[ERROR]   location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Tetrahedron.java:[333,68] cannot find symbol
[ERROR]   symbol:   method round(int)
[ERROR]   location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Tetrahedron.java:[335,68] cannot find symbol
[ERROR]   symbol:   method round(int)
[ERROR]   location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] /home/brad/develop/JOSS-review/ccg-v3d/src/main/java/uk/ac/leeds/ccg/v3d/geometry/V3D_Tetrahedron.java:[337,68] cannot find symbol
[ERROR]   symbol:   method round(int)
[ERROR]   location: class uk.ac.leeds.ccg.math.number.Math_BigRational
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException**

**Comment by agdturner** [comment]
Math_Quaternion_BigRational is in ccg-math in the path uk.ac.leeds.ccg.math.number
The version of ccg-math is 2.0.10 and this contains that class:
![image](https://user-images.githubusercontent.com/5878594/170367129-8d89b81f-c74c-492a-ad37-ab12197fedf5.png)

What version of Eclipse are you using? Same as me: Version: 2022-03 (4.23.0) Build id: 20220310-1457?

**Comment by agdturner** [comment]
Perhaps your system only partially downloaded the ccg-math dependency?

**Comment by agdturner** [comment]
I ran the tests in Eclipse and it seems like everything is fine:
![image](https://user-images.githubusercontent.com/5878594/170371108-f0bca7cb-05ad-46eb-820e-e466b00ae452.png)

**Comment by behollister** [comment]
Okay, missing "uk.ac.leeds.ccg.math.number.Math_Quaternion_BigRational." Doesn't look like my local copy has Math_Quaternion_BigRational.class under the uk.ac.leeds.ccg.math.number package (see attached screen pic).

Shouldn't that be provided by the Maven build system, as added in the POM? Is perhaps an incorrect version of the math.number package missing the Quaternion class as fetched by Maven (different from your local environment)?

![missingQuatLib](https://user-images.githubusercontent.com/20388050/170542930-f7cb31d6-fae1-4d86-89cd-597192ce6dc2.png)

**Comment by agdturner** [comment]
Sorry @behollister you are quite correct, this is not in the ccg-math version 2.0.10 Maven artefact. I have bumped the version of this dependency to 2.1 and changed the ccg-v3d pom.xml to refer to this version and updated the version of ccg-v3d to version 0.15. Can you use these new versions? Is there anything I need to do to adjust things for the JOSS review/paper? Once again I do apologise for this and thanks for your work and patients with this review. Andy

**Comment by behollister** [comment]
Hi Andy, 

Got busy the last few days with a new book proposal. Will continue with the review tomorrow. If all goes well, will try to finish up then. 

Note that there's still the other reviewer that hasn't started yet, I don't believe.

**Comment by behollister** [comment]
Yes, I have verified that the project builds and runs tests as intended.
